### PR TITLE
Add algorithm descriptions

### PR DESCRIPTION
**Pull request by zolkis**
Signed-off-by: Zoltan Kis <zoltan.kis@intel.com>

### CODE REVIEW

**Comment by zolkis** [comment]
Let's use this PR to collect algorithm descriptions. Some links for how algorithms are written elsewhere (note the standard wording and style):
https://w3c.github.io/web-nfc/#the-push-method
https://w3c.github.io/web-nfc/#the-watch-method
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-connect
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattserver-disconnect
https://fetch.spec.whatwg.org/#dom-global-fetch

**Comment by danielpeintner** [comment]
I looked at `consume` and `produce` before your PR.

The algorithm I came up with deals with the following situations (maybe also some basic stuff):

## consume
* What if passed passed td argument is not defined, or does not fulfill the requirements of a ThingDescription (how to check?)
* adding *default*  values specified in [TD-spec] (e.g., property observable/writable false or mediaType "application/json")
* what are possible errors ?

## produde
* what if the ThingModel model argument is not defined, or is neither a ThingDescription nor a ThingFragment
* adding *default*  values ?
* what are possible errors ?

Let's discuss whether this should be part of the algorithm or not in the call today.

**Comment by zolkis** [comment]
@danielpeintner @mkovatsc please check now. These are the algorithms we can ship now.
I would postpone detailed definition of register() and unregister().

**Comment by zolkis** [comment]
"WiP" flag taken off, it can be merged (after eventual fixes).

**Comment by zolkis** [comment]
Merging this because WG members prefer reviewing the master branch.

**Pull request merged**
