### PR TITLE
Separate client and server API

### PR DESCRIPTION
**Pull request by zolkis**
Fixing #173 
Other small fixes.

### CODE REVIEW

**Comment by zolkis** [comment]
@danielpeintner I'd need your input on the following.

We could further simplify the API, leaving just ConsumedThing, ExposedThing and ThingDiscovery as API entry points (constructible). But then we need to add the equivalent of consume() and produce() to them.

consume() could be moved inside ConsumedThing, renamed as `instantiate(td)`. That would also solve updating the object when the TD remotely changes.

produce() could be moved inside ExposedThing as the `instantiate(td)` method. `expose()` would work the same way. This would allow updating a TD then re-instantiate in the same ExposedThing.

Looks somewhat simpler than now with the 2 levels of interfaces.

**Comment by danielpeintner** [comment]
another alternative I see is to keep the WoT entry point mostly as it was (with consume, produce, and maybe even discover) and add
* a return code / error if a given function is not available/supported
* or maybe also a helper call to check what functionality is supported in a given implementation

Does this makes sense?

**Comment by zolkis** [comment]
Just to record the outcome of the call:
- we do away with ThingInstance
- in this version, we maintain the split. 
Feature detection is fine to be done in exception handling in Web APIs.

**Comment by zolkis** [comment]
Pretty big change in the last commit, this is the simplest API so far. 
A bit stretching the limits with the ConsumedThing constructor, but the basic validation should be really fast and if all breaks, it can be omitted from it, given that TD validation is described in / belongs to the TD spec.

**Comment by zolkis** [comment]
A TODO after the basic shape of the new API is accepted is to change all exception names to be in quotes.

**Comment by danielpeintner** [comment]
I support the simple API approach (having ConsumedThing, ExposedThing and ThingDiscovery only).

Moreover, the clean initialisation in the constructor makes perfect sense to me.

**Comment by zolkis** [comment]
Some new changes based on discussions:
- added UA conformance classes for client, server and discovery
- added back the WoT API object
- kept constructors for ConsumedThing and ExposedThing
- some small editorial changes.

**Comment by zolkis** [comment]
Amended the previous commit to add to the commit message the issue it is fixing.

**Comment by zolkis** [comment]
Review period is over, consensus between editors.
Further feedback will be handled in subsequent PR's.

**Pull request merged**
