### PR TITLE
feat: update typescript definitions

### PR DESCRIPTION
**Pull request by danielpeintner**

### CODE REVIEW

**Comment by danielpeintner** [comment]
@zolkis  @relu91 please have a look. I hope I did not miss anything ;-)

**Comment by zolkis** [comment]
At first sight looks good, but will check more thoroughly tomorrow.

**Comment by danielpeintner** [comment]
> Looks good. However, should we mark read/writeMultiple deprecated?

we could add @deprecated to the method call descriptions but at the moment we are referring to TD 1.0 which does *not* speak about any deprecation... mhh

**Comment by danielpeintner** [comment]
I tend to merge the PR now "as is" to facilitate the start of updating node-wot.

I will publish it on NPM and as `"version": "0.8.0-SNAPSHOT.1"` and we can still update if issues pop up..

**Comment by danielpeintner** [comment]
FYI: see https://www.npmjs.com/package/wot-typescript-definitions

**Pull request merged**
